"""Adiciona campos de link ao FaqPergunta

Revision ID: 0e1469f29af0
Revises: c5b051524925
Create Date: 2025-07-24 21:53:29.555511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1469f29af0'
down_revision = 'c5b051524925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq_pergunta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('link_texto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq_pergunta', schema=None) as batch_op:
        batch_op.drop_column('link_texto')
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
