"""cria tabela config_link

Revision ID: 106be02b05d2
Revises: 9e7a92b0c53f
Create Date: 2025-07-28 22:01:03.026171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106be02b05d2'
down_revision = '9e7a92b0c53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_link')
    # ### end Alembic commands ###
