"""Adiciona campos de link ao modelo Aviso

Revision ID: 1fd5ec0ffdf8
Revises: 3bdc6a47d337
Create Date: 2025-07-23 22:16:42.666188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd5ec0ffdf8'
down_revision = '3bdc6a47d337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('link_texto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso', schema=None) as batch_op:
        batch_op.drop_column('link_texto')
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###
