"""Adiciona campo de certificado ao Destaque

Revision ID: 2ce43ff89424
Revises: 1fd5ec0ffdf8
Create Date: 2025-07-23 23:18:49.232014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce43ff89424'
down_revision = '1fd5ec0ffdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destaque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('certificado_filename', sa.String(length=120), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destaque')
    # ### end Alembic commands ###
