"""Adiciona colunas cargo e time ao Colaborador

Revision ID: 2f937610fb1a
Revises: 60d7748ef8bd
Create Date: 2025-07-23 21:21:33.716865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f937610fb1a'
down_revision = '60d7748ef8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('cargo')

    # ### end Alembic commands ###
