"""Adiciona campo de foto ao Colaborador

Revision ID: 3bdc6a47d337
Revises: 2f937610fb1a
Create Date: 2025-07-23 21:49:46.557104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdc6a47d337'
down_revision = '2f937610fb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_column('foto_filename')

    # ### end Alembic commands ###
