"""Renomeia campo de certificado para imagem em Destaque

Revision ID: 4f8ed3e5c4b4
Revises: 0e1469f29af0
Create Date: 2025-07-24 22:31:55.054556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8ed3e5c4b4'
down_revision = '0e1469f29af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destaque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_filename', sa.String(length=120), nullable=True))
        batch_op.drop_column('certificado_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destaque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificado_filename', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('imagem_filename')

    # ### end Alembic commands ###
