"""Criação inicial de todas as tabelas

Revision ID: 57aede473c86
Revises: 
Create Date: 2025-07-31 00:00:15.063102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aede473c86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('conteudo', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=200), nullable=True),
    sa.Column('link_texto', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('config_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('faq_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tbOuvidoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('tipo_denuncia', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('anonima', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email_corporativo', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('foto_filename', sa.String(length=120), nullable=True),
    sa.Column('superior_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['superior_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaborador_email_corporativo'), ['email_corporativo'], unique=True)

    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=255), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=300), nullable=True),
    sa.Column('link_texto', sa.String(length=100), nullable=True),
    sa.Column('palavras_chave', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['faq_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destaque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('imagem_filename', sa.String(length=120), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destaque')
    op.drop_table('faq_pergunta')
    op.drop_table('evento')
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaborador_email_corporativo'))

    op.drop_table('colaborador')
    op.drop_table('user')
    op.drop_table('tbOuvidoria')
    op.drop_table('faq_categoria')
    op.drop_table('departamento')
    op.drop_table('config_link')
    op.drop_table('cargo')
    op.drop_table('aviso')
    # ### end Alembic commands ###
