"""Adiciona novos tipos de reacao

Revision ID: 61a1fc02afac
Revises: 27f570511b99
Create Date: 2025-08-26 22:12:51.636961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a1fc02afac'
down_revision = '27f570511b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_news_reacao', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('like', 'palmas', 'coracao', 'genial', 'feliz', 'heart', 'lightbulb', 'surprise', 'rocket', 'grin', 'hearteyes', name='news_reacao_tipo'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_news_reacao', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Enum('like', 'palmas', 'coracao', 'genial', 'feliz', 'heart', 'lightbulb', 'surprise', 'rocket', 'grin', 'hearteyes', name='news_reacao_tipo'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
