"""adiciona data_inicio ao colaborador

Revision ID: 9e7a92b0c53f
Revises: 1aaa4826bc21
Create Date: 2025-07-28 21:18:06.683153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7a92b0c53f'
down_revision = '1aaa4826bc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###
