"""primeira migration

Revision ID: ad40d7b8db57
Revises: 
Create Date: 2025-09-01 08:30:38.014081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad40d7b8db57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('conteudo', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=200), nullable=True),
    sa.Column('link_texto', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('config_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('faq_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tbOuvidoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('tipo_denuncia', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('anonima', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email_corporativo', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('foto_filename', sa.String(length=120), nullable=True),
    sa.Column('superior_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['superior_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaborador_email_corporativo'), ['email_corporativo'], unique=True)

    op.create_table('faq_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=255), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=300), nullable=True),
    sa.Column('link_texto', sa.String(length=100), nullable=True),
    sa.Column('palavras_chave', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['faq_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaborador_permissoes',
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.PrimaryKeyConstraint('colaborador_id', 'permissao_id')
    )
    op.create_table('destaque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('imagem_filename', sa.String(length=120), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_news_enquete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_selecao', sa.Enum('single', 'multi', name='news_enquete_tipo'), nullable=True),
    sa.Column('anonima', sa.Boolean(), nullable=True),
    sa.Column('vis_resultado', sa.Enum('always', 'after_vote', 'after_close', name='news_enquete_vis'), nullable=True),
    sa.Column('inicio_em', sa.DateTime(), nullable=True),
    sa.Column('fim_em', sa.DateTime(), nullable=True),
    sa.Column('fixado_ordem', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'aberta', 'encerrada', name='news_enquete_status'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_news_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo_md', sa.Text(), nullable=True),
    sa.Column('midias_json', sa.JSON(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('fixado_ordem', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'publicado', name='news_post_status'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_sentimento_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('sentimento', sa.Enum('muito_triste', 'triste', 'neutro', 'feliz', 'muito_feliz', name='sentimento_dia_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'data', name='uix_sentimento_usuario_data')
    )
    with op.batch_alter_table('tb_sentimento_dia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_sentimento_dia_data'), ['data'], unique=False)

    op.create_table('tb_news_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estrelas', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['tb_news_post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'usuario_id', name='uix_avaliacao_post_usuario')
    )
    op.create_table('tb_news_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('gif_id', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('editado_em', sa.DateTime(), nullable=True),
    sa.Column('excluido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['tb_news_post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_news_enquete_opcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquete_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enquete_id'], ['tb_news_enquete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_news_reacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('like', 'palmas', 'coracao', 'genial', 'feliz', 'heart', 'lightbulb', 'surprise', 'rocket', 'grin', 'hearteyes', name='news_reacao_tipo'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['tb_news_post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'usuario_id', name='uix_reacao_post_usuario')
    )
    op.create_table('tb_news_enquete_voto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquete_id', sa.Integer(), nullable=False),
    sa.Column('opcao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('hash_anon', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enquete_id'], ['tb_news_enquete.id'], ),
    sa.ForeignKeyConstraint(['opcao_id'], ['tb_news_enquete_opcao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquete_id', 'hash_anon', 'opcao_id', name='uix_voto_anon'),
    sa.UniqueConstraint('enquete_id', 'usuario_id', 'opcao_id', name='uix_voto_ident')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_news_enquete_voto')
    op.drop_table('tb_news_reacao')
    op.drop_table('tb_news_enquete_opcao')
    op.drop_table('tb_news_comentario')
    op.drop_table('tb_news_avaliacao')
    with op.batch_alter_table('tb_sentimento_dia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_sentimento_dia_data'))

    op.drop_table('tb_sentimento_dia')
    op.drop_table('tb_news_post')
    op.drop_table('tb_news_enquete')
    op.drop_table('evento')
    op.drop_table('destaque')
    op.drop_table('colaborador_permissoes')
    op.drop_table('faq_pergunta')
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaborador_email_corporativo'))

    op.drop_table('colaborador')
    op.drop_table('tbOuvidoria')
    op.drop_table('permissao')
    op.drop_table('faq_categoria')
    op.drop_table('departamento')
    op.drop_table('config_link')
    op.drop_table('cargo')
    op.drop_table('aviso')
    # ### end Alembic commands ###
