"""Cria tabelas para o modulo de FAQ

Revision ID: c5b051524925
Revises: 2ce43ff89424
Create Date: 2025-07-24 21:32:57.077934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b051524925'
down_revision = '2ce43ff89424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('faq_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=255), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('palavras_chave', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['faq_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_pergunta')
    op.drop_table('faq_categoria')
    # ### end Alembic commands ###
