"""add Sentimento do Dia

Revision ID: d57fc5fb35d9
Revises: 47c2b8001272
Create Date: 2025-08-31 22:31:22.166093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57fc5fb35d9'
down_revision = '47c2b8001272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_sentimento_dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('sentimento', sa.Enum('muito_triste', 'triste', 'neutro', 'feliz', 'muito_feliz', name='sentimento_dia_enum'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'data', name='uix_sentimento_usuario_data')
    )
    with op.batch_alter_table('tb_sentimento_dia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_sentimento_dia_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sentimento_dia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_sentimento_dia_data'))

    op.drop_table('tb_sentimento_dia')
    # ### end Alembic commands ###
