"""add permission system

Revision ID: e0061a47d8c5
Revises: 57aede473c86
Create Date: 2025-08-21 01:19:33.408149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0061a47d8c5'
down_revision = '57aede473c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('colaborador_permissoes',
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('permissao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['permissao_id'], ['permissao.id'], ),
    sa.PrimaryKeyConstraint('colaborador_id', 'permissao_id')
    )
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.add_column(sa.Column('colaborador_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_evento_colaborador_id_colaborador', 'colaborador', ['colaborador_id'], ['id'])

    op.drop_table('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('colaborador_id')
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_evento_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('colaborador_permissoes')
    op.drop_table('permissao')
    # ### end Alembic commands ###
