"""Cria a tabela de Ouvidoria

Revision ID: e2a73fbf945f
Revises: 4f8ed3e5c4b4
Create Date: 2025-07-24 23:26:39.632690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a73fbf945f'
down_revision = '4f8ed3e5c4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbOuvidoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('tipo_denuncia', sa.String(length=100), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('anonima', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('contato', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('responsavel', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbOuvidoria')
    # ### end Alembic commands ###
